methods:
  OVHTCP:
    - https://google.com/
    - https://google.com/
    - https://google.com/
  NFO:
    - https://google.com/
    - https://google.com/
    - https://google.com/
  DNS:
    - https://google.com/
    - https://google.com/
    - https://google.com/
